version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
      - api
      - ollama
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./web:/usr/share/nginx/html
  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    expose:
      - 8000
    environment:
      - FLASK_DEBUG=0
    volumes:
      - ./api/main.py:/app/main.py
      - ./api:/app 

   

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - 11434
    restart: unless-stopped
   

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - N8N_PORT=5678
      - N8N_HOST="IP_ADDRESS"
      - N8N_PROTOCOL=http
      #- N8N_PATH=/n8n
      - WEBHOOK_TUNNEL_URL=IP_ADDRESS
      #- WEBHOOK_URL=https://135.181.141.52/
      - N8N_SECURE_COOKIE=false
      - VUE_APP_URL_BASE_API=IP_ADDRESS
      - NODE_ENV=production
      - N8N_HOST=localhost
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      #- N8N_BASIC_AUTH_USER=jediel
      #- N8N_BASIC_AUTH_PASSWORD=jediel
      - N8N_TRUST_PROXY=true
    ports:
      - "5678:5678"
    restart: unless-stopped

